[ESP32C3_SuperMini_RFM95W]
extends = esp32_base
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_build.f_flash = 40000000L
build_flags =
  ${esp32_base.build_flags}
  -I variants/esp32c3_supermini_rfm95w
  -D ESP32_CPU_FREQ=80
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=5

  ; LoRa SPI pins for ESP32-C3 SuperMini
  -D P_LORA_SCLK=4
  -D P_LORA_MISO=5
  -D P_LORA_MOSI=6
  -D P_LORA_NSS=7

  ; Adafruit RFM95W control pins
  -D P_LORA_RESET=3
  -D P_LORA_DIO_0=10
  -D P_LORA_DIO_1=-1

  ; SX1276 / RFM95W radio
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper
  -D SX127X_CURRENT_LIMIT=120

  ; EU 868 MHz starting TX power
  -D LORA_TX_POWER=17
  

build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/esp32c3_supermini_rfm95w>
  +<helpers/sensors>

lib_deps =
  ${esp32_base.lib_deps}


[env:ESP32C3_SuperMini_RFM95W_companion_radio_wifi]
extends = ESP32C3_SuperMini_RFM95W
build_src_filter = ${ESP32C3_SuperMini_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${ESP32C3_SuperMini_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"MeshCoreTest"'
  -D WIFI_PWD='"meshcore123"'
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${ESP32C3_SuperMini_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0


[env:ESP32C3_SuperMini_RFM95W_companion_radio_ble]
extends = ESP32C3_SuperMini_RFM95W
build_src_filter = ${ESP32C3_SuperMini_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${ESP32C3_SuperMini_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${ESP32C3_SuperMini_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0


[env:ESP32C3_SuperMini_RFM95W_companion_radio_usb]
extends = ESP32C3_SuperMini_RFM95W
build_src_filter = ${ESP32C3_SuperMini_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${ESP32C3_SuperMini_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${ESP32C3_SuperMini_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0
