[ESP32_WROOM_RFM95W]
extends = esp32_base
board = esp32dev

build_flags =
  ${esp32_base.build_flags}
  -I variants/esp32_wroom_rfm95w

  -D CORE_DEBUG_LEVEL=5

  ; VSPI pins for ESP32-WROOM
  -D P_LORA_SCLK=18
  -D P_LORA_MISO=19
  -D P_LORA_MOSI=23
  -D P_LORA_NSS=5

  ; Adafruit RFM95W control pins
  -D P_LORA_RESET=14
  -D P_LORA_DIO_0=27
  -D P_LORA_DIO_1=-1

  ; SX1276 / RFM95W
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper
  -D SX127X_CURRENT_LIMIT=120
  -D LORA_TX_POWER=17

build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/esp32_wroom_rfm95w>
  +<helpers/sensors>

lib_deps =
  ${esp32_base.lib_deps}


[env:ESP32_WROOM_RFM95W_companion_radio_usb]
extends = ESP32_WROOM_RFM95W

build_src_filter = ${ESP32_WROOM_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>

build_flags =
  ${ESP32_WROOM_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256

lib_deps =
  ${ESP32_WROOM_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0


[env:ESP32_WROOM_RFM95W_companion_radio_ble]
extends = ESP32_WROOM_RFM95W

build_src_filter = ${ESP32_WROOM_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>

build_flags =
  ${ESP32_WROOM_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256

lib_deps =
  ${ESP32_WROOM_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0


[env:ESP32_WROOM_RFM95W_companion_radio_wifi]
extends = ESP32_WROOM_RFM95W

build_src_filter = ${ESP32_WROOM_RFM95W.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>

build_flags =
  ${ESP32_WROOM_RFM95W.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"MeshCoreTest"'
  -D WIFI_PWD='"meshcore123"'

lib_deps =
  ${ESP32_WROOM_RFM95W.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0
